config:
  backup: false
  create: true
  dotpath: dotfiles
actions:
  pre:
    macOs_fonts_install: brew tap homebrew/cask-fonts
    macOs_source_code_font_install: brew install --cask font-sauce-code-pro-nerd-font; echo -e "\xf0\x9f\x90\x8d"; echo -e "\xee\x82\xa0"
    starship_install: command -v starship || (brew install starship)
    alacritty_install: command -v alacritty || (brew install alacitty)
    nvm_install: test -e $HOME/.config/nvm || (curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh
      | bash)
    antidote_install: test -e $HOME/.antidote || (git clone --depth=1 https://github.com/mattmc3/antidote.git
      $HOME/.antidote)
    fzf_install: test -e $HOME/.fzf.zsh || (git clone --depth 1 https://github.com/junegunn/fzf.git
      $HOME/.fzf; $HOME/.fzf/install)
    fzf_tab_install: test -e $HOME/fzf-tab || (git clone https://github.com/Aloxaf/fzf-tab
      $HOME/fzf-tab)
dotfiles:
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
    actions:
    - alacritty_install
    - macOs_fonts_install
    - macOs_source_code_font_install
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    chmod: '600'
    actions:
    - nvm_install
    - antidote_install
    - fzf_install
    - fzf_tab_install
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
    actions:
    - starship_install
    - macOs_fonts_install
    - macOs_source_code_font_install
profiles:
  personal:
    dotfiles:
    - d_alacritty
    - d_nvim
    - f_zshrc
    - f_starship.toml
