// Verification-only Playwright must be supplied through NODE_PATH, not vendored.
const fs=require('fs'),assert=require('assert'),{chromium}=require('playwright');
(async()=>{const base=process.argv[2];const browser=await chromium.launch({executablePath:process.env.CHROMIUM,headless:true});const results=[];
for(const [name,times] of [['proof/fixture',[.5,1.5,2.5,.5]],['resize',[.5,2.5,3.5,4.5,.5]],['primary',JSON.parse(fs.readFileSync(process.argv[3])).map(c=>c.time)]]){
 const page=await browser.newPage({viewport:{width:412,height:915}});const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.route(/^https?:/,r=>r.abort());const url='file://'+base+'/'+name+'/phone.html';await page.goto(url);await page.evaluate(()=>player.play());await page.evaluate(()=>player.pause());const frames=[];
 for(const t of times){await page.evaluate(t=>player.seek(t),t);await page.waitForTimeout(200);const f=await page.evaluate(()=>{const text=snapshot();selectFrame();return {text,selected:getSelection().toString()};});assert.equal(f.text,f.selected);assert(f.text.includes('\n'));frames.push(f.text);}
 if(name==='proof/fixture'){assert(frames[0].includes('RED      GAP'));assert(frames[0].includes('界  X'));assert(frames[0].includes('é  Y'));assert(frames[0].includes('<script></script>'));assert(frames[1].includes('ALTERNATE'));assert(frames[2].includes('RESTORED'));assert.equal(frames[0],frames[3]);}
 if(name==='resize')assert.equal(frames[0],frames[4]);
 if(name==='primary' && process.argv[4]){const original=await browser.newPage({viewport:{width:412,height:915}});await original.goto('file://'+process.argv[4]);await original.evaluate(()=>player.play());await original.evaluate(()=>player.pause());for(let i=0;i<times.length;i++){await original.evaluate(t=>player.seek(t),times[i]);await original.waitForTimeout(200);assert.equal(await original.evaluate(()=>snapshot()),frames[i]);}await original.close();}
 if(name==='primary'){assert(frames.some(f=>f.includes('ZZZ-END-DIGEST-VERIFIED')));assert(frames.some(f=>f.includes('Latest good recap')));assert(await page.locator('#chapters button').count()>0);await page.locator('#chapters button').nth(1).click();await page.waitForTimeout(250);assert((await page.locator('#frame').textContent()).includes('Herdr Overview'));}
 await page.reload();assert.equal(errors.length,0);assert(requests.every(r=>r===url));results.push({name,requests,errors,frames});await page.close();}
 await browser.close();fs.writeFileSync(base+'/browser-receipt.json',JSON.stringify(results,null,2));console.log('PASS: offline seek/chapters/select Unicode rows/gaps, primary original frames, resize');})().catch(e=>{console.error(e);process.exit(1)});
